### ISSUE TITLE
Publish package to npm

### ISSUE THREAD

**Issue by jdlehman** [at-import/Sassy-Maps#14]
Can we get this on npm?  I am trying to consume sassy-maps in a node build environment with node-sass.  The sassy-maps name is currently available on npm

**Comment by safareli** [comment]
+1

**Comment by joseluis** [comment]
This now works ([source](https://docs.npmjs.com/cli/install)):
`npm install github:at-import/Sassy-Maps`

**Comment by strarsis** [comment]
Awesome "github:" method with npm, thanks!

I had to specify a release semver tag because in the head/master some files were missing:

```
npm install github:at-import/Sassy-Maps#v0.4.0
```

**Comment by Undistraction** [comment]
+1 Everyone seems to have ditched or be ditching Bower, so please publish to npm.

**Comment by niksy** [comment]
Also looking for this, is this possible to get published to npm? What can we do to help with this issue?

**Comment by ncoden** [comment]
Poke @HugoGiraudel ;)

**Comment by KittyGiraudel** [comment]
I’ll see if I can do that. Maybe @scottkellum or @Snugug want to have a word on this?

**Comment by ncoden** [comment]
@jdlehman Why closing ?
@HugoGiraudel With Eyeglass please :)

**Comment by KittyGiraudel** [comment]
Could you PR it for Eyeglass support maybe?

**Comment by strarsis** [comment]
@HugoGiraudel: https://github.com/at-import/Sassy-Maps/pull/17
Also closes https://github.com/at-import/Sassy-Maps/issues/15 .

**Comment by KittyGiraudel** [comment]
Oh, I just realised it was on Sassy-Maps repository. It’s not my project at all, haha. I didn’t contribute to it and don’t have rights over it. Sorry!
