### ISSUE TITLE
Use map-keys instead of get-keys

### ISSUE THREAD

**Issue by KittyGiraudel** [at-import/Sassy-Maps#2]
Why not using the built-in `map-keys` function instead of your own `get-keys` function to get the keys from a map?

https://github.com/nex3/sass/blob/master/doc-src/SASS_CHANGELOG.md#sassscript-maps

**Comment by Snugug** [comment]
They do different things. `get-keys` is a helper function to return the list of keys to to pass into `map-get-deep`, which itself uses `map-get`. The semantics for that are "keys for get" instead of "get me keys"
