### ISSUE TITLE
licensing too vague

### ISSUE THREAD

**Issue by jonassmedegaard** [at-import/Sassy-Maps#8]
It seems licensing of this project is currently only reflected in gemspec file as "MIT".

"MIT" licensing - although a popular label - is arguably ambiguous, so it is recommended to reference a URL to the actual licensing terms (which for "MIT" is often what some label less ambiguously as "Expat" license).

Please add unambiguous licensing statement - e.g. like the README.md section in your breakpoint project.

**Comment by Snugug** [comment]
You're totally right! Resolved!

**Comment by jonassmedegaard** [comment]
Quoting Sam Richard (2014-11-12 12:49:24)

> You're totally right!

Thanks for the compliment.  Here's one for you: You are totally cool!

A hint if you wanna continue this "duel": Today is my birthday :-D

> Resolved!

Excellent!
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jtjeferreira** [comment]
@Snugug can you release/tag a version with the License included? I was trying to create a webjars version of sassy-maps but have the following error

`Failed! All attempts to determine an acceptable license have been exhausted. The bower.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: git://github.com/at-import/Sassy-Maps.git The acceptable open source software licenses are at: https://bintray.com/docs/api/#_footnote_1 The provided licenses were:  This problem will likely need to be resolved by working with the library maintainers directly. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Got Bower info Determined Artifact Name: sassy-maps Starting Deploy`
